// GENERATED BY YOU (or flutterfire configure)
// DO NOT COMMIT REAL KEYS PUBLICLY

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 🌐 WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "WEB_API_KEY",
    appId: "WEB_APP_ID",
    messagingSenderId: "SENDER_ID",
    projectId: "PROJECT_ID",
    authDomain: "PROJECT_ID.firebaseapp.com",
    storageBucket: "PROJECT_ID.appspot.com",
  );

  // 🤖 ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "ANDROID_API_KEY",
    appId: "ANDROID_APP_ID",
    messagingSenderId: "SENDER_ID",
    projectId: "PROJECT_ID",
    storageBucket: "PROJECT_ID.appspot.com",
  );

  // 🪟 WINDOWS
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "WINDOWS_API_KEY",
    appId: "WINDOWS_APP_ID",
    messagingSenderId: "SENDER_ID",
    projectId: "PROJECT_ID",
    authDomain: "PROJECT_ID.firebaseapp.com",
    storageBucket: "PROJECT_ID.appspot.com",
  );

  // 🍎 IOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "IOS_API_KEY",
    appId: "IOS_APP_ID",
    messagingSenderId: "SENDER_ID",
    projectId: "PROJECT_ID",
    storageBucket: "PROJECT_ID.appspot.com",
    iosBundleId: "com.example.bingoapp",
  );

  // 💻 MACOS (optional)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "MACOS_API_KEY",
    appId: "MACOS_APP_ID",
    messagingSenderId: "SENDER_ID",
    projectId: "PROJECT_ID",
    storageBucket: "PROJECT_ID.appspot.com",
  );
}
